### ISSUE TITLE
Le AltisMOTDCore !!

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [Rubyliss/Altis-RP#1]
J'ai regardé le skript et conclu que se skript n'est pas a toi !! il vient d'ici (https://www.spigotmc.org/resources/the-server-motd.30447/).
Tu deverais supprimer le fichier pour ne pas avoir d'enmerde :)
c'est dommage que tu soit partit, bonne continuation
Tom

**Comment by Rubyliss** [comment]
En effets j'avais oublié que cette partie était la seul que j'avais pris du net.

Ça sera rajouté dans le Read.me, je continue de skripter de mon côté, j'aimerai bien faire du Open source sauf que pour se coup là j'ai eu des consigne de confidentialité.
