### ISSUE TITLE
Altis-Rp n'est pas ta propriété

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [Rubyliss/Altis-RP#2]
Par contre je vais te demander de changer le nom de ce repo GitHub
Tu peut l'appeler
"RpSkripts" par exemple

Merci , Bonne continuation
Tom

**Comment by Rubyliss** [comment]
Les skripts on été réalisé originalement pour le servuer, et en aucun cas je revendique le nom "Altis RP" seul les skript on la licence.
Le nom Altis RP n'est d'ailleurs par déposé par vous, de se fait je n'est aucune obligation de changé le nom du Repo.

Cependant je comprends le problème et je vais changé le du répo.
Inutile de crée de nouvelle issue pour ça

**Comment by TomAvecLeVdsl** [comment]
Pas de probleme et merci d'avoir changer le nom :) en espetant que tu vas continuer a skripter :) bonne continuation
